### ISSUE TITLE
ABN import error: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by owoshch** [mapillary/inplace_abn#102]
I have troubles using ABN. I'm aware of similar issues. I've installed CUDA 9.2 and it didn't help.
Do you have any recommendations on this?

Ubuntu 18.04.1 LTS

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

gcc --version
gcc (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cat /usr/local/cuda/version.txt:
CUDA Version 9.2.88
CUDA Patch Version 9.2.88.1

`/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:166: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
Traceback (most recent call last):
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validate.py", line 1, in <module>
    from modules import ABN
  File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': [1/5] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
FAILED: inplace_abn_cpu.o 
c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
In file included from /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp:1:
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:3:
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Allocator.h:2:
/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/c10/core/Allocator.h:4:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
[2/5] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
FAILED: inplace_abn_cuda_half.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
In file included from /usr/local/cuda/include/common_functions.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:93:15: fatal error: new: No such file or directory
 #include <new>
               ^
compilation terminated.
[3/5] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
In file included from /usr/local/cuda/include/common_functions.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:93:15: fatal error: new: No such file or directory
 #include <new>
               ^
compilation terminated.
[4/5] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp -o inplace_abn.o
FAILED: inplace_abn.o 
c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp -o inplace_abn.o
In file included from /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp:1:
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:4:
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h:3:
/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.`

**Comment by rotabulo** [comment]
@owoshch can you simply try to let `c++` point to `g++` ?

**Comment by owoshch** [comment]
Which command should I use for that?

**Comment by rotabulo** [comment]
@owoshch `sudo ln -s /usr/bin/g++ /usr/bin/c++` but you should probably first uninstall the c++ you have installed, or you make sure that the aliased `c++` is in the search path before `/usr/bin` .

**Comment by owoshch** [comment]
I've done this and got a new error pointing out that I don't have an essential include <new> in memory file. 
The solution is to reinstall libstd: `sudo apt install --reinstall libstdc++-7-dev`
Thanks for help!
`File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': [1/5] c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
FAILED: inplace_abn_cpu.o 
c++ -MMD -MF inplace_abn_cpu.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp -o inplace_abn_cpu.o
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/Allocator.h:2:0,
                 from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:3,
                 from /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cpu.cpp:1:
/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/c10/core/Allocator.h:4:10: fatal error: memory: No such file or directory
 #include <memory>
          ^~~~~~~~
compilation terminated.
[2/5] c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp -o inplace_abn.o
FAILED: inplace_abn.o 
c++ -MMD -MF inplace_abn.o.d -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -O3 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp -o inplace_abn.o
In file included from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/all.h:3:0,
                 from /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/extension.h:4,
                 from /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn.cpp:1:
/home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: cstddef: No such file or directory
 #include <cstddef>
          ^~~~~~~~~
compilation terminated.
[3/5] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
FAILED: inplace_abn_cuda.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
In file included from /usr/local/cuda/include/cuda_runtime.h:115:0,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:103:10: fatal error: new: No such file or directory
 #include <new>
          ^~~~~
compilation terminated.
[4/5] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
FAILED: inplace_abn_cuda_half.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/fedor.kitashov/anaconda3/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/fedor.kitashov/anaconda3/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/fedor.kitashov/test_pytorch_10/inplace_abn/modules/src/inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
In file included from /usr/local/cuda/include/cuda_runtime.h:115:0,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:103:10: fatal error: new: No such file or directory
 #include <new>
          ^~~~~
compilation terminated.
ninja: build stopped: subcommand failed.`

**Comment by sbelharbi** [comment]
Hi,
   I made it work on two servers (ubuntu 16, cuda 9.1, gcc 5.4), but not on my computer (ubuntu  18.04, cuda 9.1, gcc 6.5) which has similar configuration as @owoshch 

did you figure it out how to fix this? (not clear in your last message @owoshch ) Thanks!

**Comment by sbelharbi** [comment]
Fix: https://github.com/mapillary/inplace_abn/issues/106#issuecomment-475460496
