### ISSUE TITLE
inplace_ABN is not working with pytorch 1.3

### ISSUE THREAD

**Issue by mrT23** [mapillary/inplace_abn#145]
when I try to install ABN with PyTorch 1.3 I get an error message:
"
 src/inplace_abn_cpu.cpp:76:28: error: call of overloaded 'mean(<brace-enclosed initializer list>)' is ambiguous
     auto mean = x.mean({0, 2});
"

in PyTorch 1.2 the installation works

**Comment by mattzque** [comment]
#144

**Comment by ducksoup** [comment]
This is now fixed.
